name: Pull Request

on:
  pull_request:

jobs:
  validate-lint-eslint:
    runs-on: ubuntu-latest
    name: Validate lint - ESLint
    steps:
      - name: ESLint
        uses: eviive/actions/validate/lint/eslint@main
        with:
          token: ${{ secrets.REVIEWDOG_GITHUB_API_TOKEN }}

  validate-format-prettier:
    runs-on: ubuntu-latest
    name: Validate format - Prettier
    steps:
      - name: Prettier
        uses: eviive/actions/validate/format/prettier@main
        with:
          token: ${{ secrets.REVIEWDOG_GITHUB_API_TOKEN }}
